---
title: "Untitled"
output: html_document
---

## Carga de bibliotecas
```{r}
library(graphics)
library(ggplot2)
library(dplyr)
library(gridExtra)

```


```{r}
Liberia_datos.climaticos <- read.csv("Liberia_datos climaticos.csv",
                                     sep = ",",
                                     na.strings = "0,00",
                                     dec = ",")
```


# Limpieza de datos

```{r}
Liberia_datos.climaticos <- na.omit(Liberia_datos.climaticos)
```

```{r}
head(Liberia_datos.climaticos)
```
 
```{r}
dim(Liberia_datos.climaticos)
```

 




```{r}
Temp <- ggplot(data = Liberia_datos.climaticos, aes(x = Temperatura..Celsius.)) + geom_histogram(binwidth = 2,
 color = "red",
 fill = "white") +
  facet_grid()
```

```{r}
HumR <- ggplot(data = Liberia_datos.climaticos, aes(x = HumedadRelativa....,)) + geom_histogram(binwidth = 2, 
color = "green",                
fill= "white") +
  facet_grid()

```


```{r}
VelV <- ggplot(data = Liberia_datos.climaticos, aes(x = VelocidadViento..m.s.))+ geom_histogram(binwidth = 2,
 color = "purple",
 fill = "white") +
  facet_grid()
```



```{r}
LLuv <- ggplot(data = Liberia_datos.climaticos, aes(x = Lluvia..mm.))+ geom_histogram(binwidth = 2,
 color = "blue",
 fill = "white") +
  facet_grid()
```



```{r}
Irr <- ggplot(data = Liberia_datos.climaticos, aes(x = Irradiacion..W.m2.))+ geom_histogram(binwidth = 2,
 color = "orange",
 fill = "white") +
  facet_grid()
```



```{r}
 EvaT <- ggplot(data = Liberia_datos.climaticos, aes(x = EvapoTranspiracion..mm.))+ geom_histogram(binwidth = 2,
 color = "pink",
 fill = "grey") +
  facet_grid()
```


## 6 variables en un panel.

```{r}
grid.arrange(Temp,HumR, VelV, LLuv, Irr,EvaT, nrow = 2) 
```


```{r}
Promedio_datos <- Liberia_datos.climaticos %>%
  select(Date, HumedadRelativa...., VelocidadViento..m.s., Lluvia..mm., Irradiacion..W.m2., EvapoTranspiracion..mm., Temperatura..Celsius.) %>%
  mutate(Date = as.Date(Date, format = "%d/%m/%y")) %>%
  group_by(Date = format(Date, "%m")) %>% 
  summarise(HumedadRelativa.... = mean(HumedadRelativa....), VelocidadViento..m.s. = mean(VelocidadViento..m.s.), Lluvia..mm. = sum(Lluvia..mm.), Irradiacion..W.m2. = mean(Irradiacion..W.m2.), EvapoTranspiracion..mm. = sum(EvapoTranspiracion..mm.), Temperatura..Celsius. = mean(Temperatura..Celsius.))
```


```{r}

I.grafico <- ggplot(Promedio_datos, aes(x=Date, y=Temperatura..Celsius., group = 1 )) + geom_line()

```

```{r}
graficoII <- ggplot(Promedio_datos, aes(x=Date, y=HumedadRelativa...., group = 1 )) + geom_line()

```

```{r}
tercero <- ggplot(Promedio_datos, aes(x=Date, y=VelocidadViento..m.s., group = 1 )) + geom_line()

```

```{r}
cuarto <- ggplot(Promedio_datos, aes(x=Date, y=Lluvia..mm., group = 1 )) + geom_line()

```

```{r}
quinto <- ggplot(Promedio_datos, aes(x=Date, y=Irradiacion..W.m2., group = 1 )) + geom_line()

```

```{r}
sexto <- ggplot(Promedio_datos, aes(x=Date, y=EvapoTranspiracion..mm., group = 1 )) + geom_line()

```


## Segunda parte, grafios de lineas. 
```{r}
grid.arrange(I.grafico, graficoII, tercero, cuarto, quinto, sexto, nrow = 2)
```


## Tercera parte

 
```{r}
f <- ggplot(Promedio_datos, aes(x=Date, y=Temperatura..Celsius., group = 1 )) + geom_point()

```

```{r}
e <- ggplot(Promedio_datos, aes(x=Date, y=HumedadRelativa...., group = 1 )) + geom_point()

```

```{r}
d <- ggplot(Promedio_datos, aes(x=Date, y=VelocidadViento..m.s., group = 1 )) + geom_point()

```

```{r}
c <- ggplot(Promedio_datos, aes(x=Date, y=Lluvia..mm., group = 1 )) + geom_point()

```

```{r}
b <- ggplot(Promedio_datos, aes(x=Date, y=Irradiacion..W.m2., group = 1 )) + geom_point()

```

```{r}
a <- ggplot(Promedio_datos, aes(x=Date, y=EvapoTranspiracion..mm., group = 1 )) + geom_point()
```

```{r}
grid.arrange(f, e, d, c, a, b, nrow = 2)
```


